<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WIN-L2TNJ7VR6RN" name="testng.chuTest" tests="1" failures="0" timestamp="28 Dec 2018 00:55:25 GMT" time="0.511" errors="1">
  <testcase name="chu10" time="0.511" classname="testng.chuTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.chu10() didn&#039;t finish within the time-out 500">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.chu10() didn't finish within the time-out 500
	at java.util.HashSet.remove(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- chu10 -->
</testsuite> <!-- testng.chuTest -->
